### ISSUE TITLE
Show network error on the webapp if internet is cut off

### ISSUE THREAD

**Issue by abhijitramesh** [Amrita-Medical-AI/eusml-labeller#13]
Currently the network stops in between the procedure but as the webapp has already been loaded on the phone it seems to be working fine. But when the procedure stops the final post request is not made and we do not end up getting the data. We need a function to continuously check for network error and show a warning to the user if a network error is reported.

**Comment by anshuman-8** [comment]
![image](https://github.com/Amrita-Medical-AI/eusml-labeller/assets/90995338/01ba5db5-2884-4475-8c43-42651d4e15e6)
We can have a pop-up like above showing an error/alert ?

**Comment by abhijitramesh** [comment]
> ![image](https://private-user-images.githubusercontent.com/90995338/293168213-01ba5db5-2884-4475-8c43-42651d4e15e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjcxNDQsIm5iZiI6MTcwMzg2Njg0NCwicGF0aCI6Ii85MDk5NTMzOC8yOTMxNjgyMTMtMDFiYTVkYjUtMjg4NC00NDc1LThjNDMtNDI2NTFkNGUxNWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE2MjA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiM2Y2OTJjYWY0NjIyZmI5NTU3MGJkOGUzYTQ0ODk3NmIxMDA4ODI1YzBkOTIyOWY4YzFkYWI5OGRiM2FmNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.idpTk2MTY1GPr07bDyH9HAsMoFvp8-mpAv6CQRXkN-I) We can have a pop-up like above showing an error/alert ?

Yes please
